version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    machine: true
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run:
          name: Install Tarpaulin
          command: |
            cargo install cargo-tarpaulin
      - run: 
          name: Running Test
          command: |
            cargo test
      - run: 
          name: Creating .xml test report
          command: |
            cargo tarpaulin --out Xml
      - codecov/upload:
          file: coverage.xml